version: "3.8"

services:
  gastro-cultures-db:
    image: postgres:13-alpine
    container_name: "parcial-apis"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=parcial
    networks:
      - parcial-net

volumes:
  postgres_data:

networks:
  parcial-net:
    driver: bridge
